# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

umask 027
export HISTCONTROL=erasedups

# start virtualbox
#echo 'starting virtual machine: Debian-Server'
#VBoxManage startvm Debian-Server --type headless
