# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Start bash_completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

export SYSTEM='Mac'
export LANG='en_US.UTF-8'
export GOPATH=~/Library/Gopath
export WORKSPACE=~/workspace
export GOPATH=$GOPATH:$WORKSPACE/dds-inspector
export GOPATH=$GOPATH:$WORKSPACE/influxdb

export PATH=~/Library/Gopath/bin:$PATH

# Source diy definitions
if [ -f ~/.bashrc.inc ]; then
	. ~/.bashrc.inc
fi

