# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Start bash_completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

export SYSTEM='Linux'

# Source diy definitions
if [ -f ~/.bashrc.inc ]; then
	. ~/.bashrc.inc
fi

